models:
  - name: "Granite"
    model_id: granite32-8b
    url: https://granite32-8b-llama-serve.apps.ocp-beta-test.nerc.mghpcc.org
    api_key: null
    cost: cheap

  - name: "Qwen 3"
    model_id: Qwen/Qwen3-8B
    url: https://qwen3-8b-tool-rag.apps.ocp-beta-test.nerc.mghpcc.org
    api_key: null
    cost: moderate

  - name: "GPT 5.1"
    model_id: gpt-5.1
    url: https://api.openai.com
    api_key: "YOUR_GATEWAY_KEY"
    cost: expensive
